# Generated by Django 5.1.5 on 2025-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="User profile picture", null=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="birth_date",
            field=models.DateField(blank=True, help_text="User's date of birth", null=True, verbose_name="Birth Date"),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="city",
            field=models.CharField(
                blank=True, help_text="User's city of residence", max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's contact phone number",
                max_length=20,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
    ]
